spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: dding
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  profiles:
    include: private

server:
  port: 40040
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
  configuration:
    cache-enabled: false
    jdbc-type-for-null: NULL
logging:
  level:
    org.springframework: debug
    org.springframework.web: debug
